server:
  port: ${SERVER_PORT}                          # ?? ?? ??

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}           # ?? ???? ??

  # Database ??
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update                              # ?? ????? update, ????? validate
    show-sql: true                                  # SQL ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# ?? ??
logging:
  level:
    com.starmeet.api: DEBUG                           # ?????? ?? ??
    org.springframework.security: DEBUG               # Security ?? ??
    org.springframework.web.socket: DEBUG             # WebSocket ?? ??
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ??? ??
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}            # 24?? (???)
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  webrtc:
    stun-server: ${STUN_SERVER}
    turn-server: ${TURN_SERVER}
    turn-username: ${TURN_USERNAME}
    turn-password: ${TURN_PASSWORD}

---
# ?? ?? ??
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update                                # ????? ?? ??? ????
    show-sql: true

---
# ?? ??
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate                              # ????? ??? ???
    show-sql: false                                   # ????? SQL ?? ????
logging:
  level:
    com.starmeet.api: INFO                            # ????? INFO ??